from args_config import get_args
from random import randrange

args = get_args()

config = {
    "N_ITERATIONS": args.N_ITERATIONS,
    "N_ITERATIONS_SAVED": args.N_ITERATIONS_SAVED,
    "IMAGE_SHAPE_X": args.IMAGE_SHAPE_X,
    "IMAGE_SHAPE_Y": args.IMAGE_SHAPE_Y,
    "IMAGE_SHAPE_Z": args.IMAGE_SHAPE_Z,
    "INITIAL_VESSEL_X_COORD": args.INITIAL_VESSEL_X_COORD,
    "INITIAL_VESSEL_Y_COORD": args.INITIAL_VESSEL_Y_COORD,
    "INITIAL_VESSEL_Z_COORD": args.INITIAL_VESSEL_Z_COORD,
    "INITIAL_PARENT_RADIUS": args.INITIAL_PARENT_RADIUS,
    "VESSEL_REPULSION_RADIUS": randrange(args.VESSEL_REPULSION_RADIUS_LOWER, args.VESSEL_REPULSION_RADIUS_UPPER),
    "VESSEL_REPULSION_STRENGTH": args.VESSEL_REPULSION_STRENGTH,
    "BRAIN_REPULSION_RADIUS": args.BRAIN_REPULSION_RADIUS,
    "BRAIN_REPULSION_STRENGTH": args.BRAIN_REPULSION_STRENGTH,
    "UPPER_STEPSIZE": args.UPPER_STEPSIZE,
    "LOWER_STEPSIZE": args.LOWER_STEPSIZE,
    "THRESHOLD": args.THRESHOLD,
    "LOWER_WIGGLE_RANGE": args.LOWER_WIGGLE_RANGE,
    "UPPER_WIGGLE_RANGE": args.UPPER_WIGGLE_RANGE,
    "RADIUS_THRESHOLD": args.RADIUS_THRESHOLD,
    "INITIAL_VESSEL_LENGTH": randrange(args.INITIAL_VESSEL_LENGTH_LOWER, args.INITIAL_VESSEL_LENGTH_UPPER),
    "LOWER_LENGTH_RANGE_LOW_RADII": args.LOWER_LENGTH_RANGE_LOW_RADII,
    "UPPER_LENGTH_RANGE_LOW_RADII": args.UPPER_LENGTH_RANGE_LOW_RADII,
    "LOWER_LENGTH_RANGE_HIGH_RADII": args.LOWER_LENGTH_RANGE_HIGH_RADII,
    "UPPER_LENGTH_RANGE_HIGH_RADII": args.UPPER_LENGTH_RANGE_HIGH_RADII,
    "UNCONTINUOUS_PARAMETER": args.UNCONTINUOUS_PARAMETER,
    "BIFURCATION_TRIFURCATION_TOTAL_PROB": args.BIFURCATION_TRIFURCATION_TOTAL_PROB,
    "UNREALISTIC_BRANCHING_RANGE_LOWER": args.UNREALISTIC_BRANCHING_RANGE_LOWER,
    "UNREALISTIC_BRANCHING_RANGE_UPPER": args.UNREALISTIC_BRANCHING_RANGE_UPPER,
    "REALISTIC_ANGLES_PARAMETER": args.REALISTIC_ANGLES_PARAMETER,
    "SAVE_DIRECTORY": '/gpfs/users/a1836131/FINAL_HPC_SYNTHETIC_VESSEL_GENERATION_CODE/SYNTHETIC_GENERATOR/SYNTHETIC_DATA',
    "BRAIN_EDGE_KERNEL_VECTOR_PATH": f"/gpfs/users/a1836131/FINAL_HPC_SYNTHETIC_VESSEL_GENERATION_CODE/BRAIN_EDGE_REPULSION_FORCE_CONVOLUTION_FILTER/Vector_Edge_Image_{args.BRAIN_REPULSION_RADIUS}.nii.gz",
    "IMAGE_BOUNDS_BRAIN_MASK": '/gpfs/users/a1836131/FINAL_HPC_SYNTHETIC_VESSEL_GENERATION_CODE/BRAIN_MASKS/output_brainmask_20230829203315.nii.gz',
    "BRAIN_MASK": '/gpfs/users/a1836131/FINAL_HPC_SYNTHETIC_VESSEL_GENERATION_CODE/BRAIN_MASKS/output_brainmask_distance_20230918204255.nii.gz',
    "PV_CSV_FILE": '/gpfs/users/a1836131/FINAL_HPC_SYNTHETIC_VESSEL_GENERATION_CODE/final_pv.csv'
}

def get_config():
    return config